baseURL = "https://codethat-today.onrender.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContenLanguageInSubdir = "true"
title = "Top Quality Developer Tutorials CodeThat.today"
Paginate = 10
pygmentsUseClasses = true
pygmentsCodeFences = true
canonifyurls = true
theme = "vsdocs"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  level = "levels"

[[menu.main]]
    name = "Go"
    weight = -100
    url = "/categories/go/"
[[menu.main]]
    name = "Python"
    weight = -90
    url = "/categories/python/"
[[menu.main]]
    name = "Typescript"
    weight = -80
    url = "/categories/typescript/"
[[menu.main]]
    name = "Clojure"
    weight = -70
    url = "/categories/clojure/"
[[menu.main]]
    name = "Scala"
    weight = -60
    url = "/categories/scala/"
[[menu.main]]
    name = "Books"
    weight = -50
    url = "/books/"

[[menu.main]]
    name = "more"
    weight = -40
    url = "/"

[[menu.main]]
    parent = "more"
    name = "Software Engineering"
    weight = -100
    url = "/categories/software-engineering/"

[[menu.footer]]
    name = "About"
    weight = -100
    url = "/about"

[[menu.footer]]
    name = "Privacy Policy"
    weight = -100
    url = "/privacy/"

[Params]
  RSSLink = "/index.xml"
  author = "theodesp"
  github = "theodesp"
  twitter = "@nerdokto"
  email = "thdespou@hotmail.com"
  sharing = true
  dateFormatToUse = "2006-01-02"
  orgName = "CodeThat.today"
  mainSections = ["article", "tutorial"]
  copyright = "Code snippets licensed under MIT, unless otherwise noted © 2019"

